version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
    env_file:
      - environments/local.env
    environment:
                CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL}}
