version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
    env_file:
      - environments/local.env
    environment:
                CONFIG_FILE_URL: https://gist.githubusercontent.com/Rajveer0916/6731cf5c353cd96e16768ded365f6358/raw/config.env
